services:
  backend-db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend-app:
    build: .
    ports:
      - "3000:3000"   # HTTP API
      - "9229:9229"   # DEBUG (Chrome DevTools)
    depends_on:
      - backend-db
    volumes:
      - .:/app        # важливо для HOT RELOAD (nodemon)
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      - CACHE_DIR=./cache
      - DB_HOST=backend-db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydb
