version: '3.9'

services:
  backend-db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend-app:
    build: .
    command: npx nodemon index.js --watch . --exec "node --inspect=0.0.0.0:9229"
    volumes:
      - .:/app
      - ./cache:/app/cache
      - ./uploads:/app/uploads
    ports:
      - "3000:3000"
      - "9229:9229"  # порт для debug через Chrome
    environment:
      DB_HOST: backend-db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
      HOST: 0.0.0.0
      PORT: 3000
      CACHE_DIR: ./cache
    depends_on:
      - backend-db
